# Generated by Django 2.2.1 on 2019-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_user',
            name='gender',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
