# Generated by Django 2.2.1 on 2019-05-22 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0005_auto_20190523_0313'),
        ('Doctor', '0004_doctor_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomsMedicine', models.TextField(default='NA')),
                ('extraMediceine', models.TextField(blank=True)),
                ('doctor', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete='models.CASCADE', to='patient.Patient')),
            ],
        ),
    ]
