# Generated by Django 2.2.1 on 2019-05-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_auto_20190523_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='symptoms',
            field=models.TextField(blank=True, default='NA'),
        ),
    ]
