# Generated by Django 2.2.1 on 2019-05-11 22:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 22, 43, 11, 312271, tzinfo=utc)),
        ),
    ]
