# Generated by Django 2.2.1 on 2019-05-18 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20190512_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 16, 17, 54, 99718, tzinfo=utc)),
        ),
    ]
