# Generated by Django 2.2.1 on 2019-05-22 22:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20190518_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 22, 13, 46, 366895, tzinfo=utc)),
        ),
    ]
