# Generated by Django 2.2.1 on 2019-05-23 00:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20190523_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 0, 0, 5, 860765, tzinfo=utc)),
        ),
    ]
