# Generated by Django 2.2.1 on 2019-05-23 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20190523_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 20, 12, 11, 705969, tzinfo=utc)),
        ),
    ]
